stages:
  proc_imgs:
    cmd: python ./utils/ImgProcess.py
    deps:
    - ./utils/ImgProcess.py
    - data/raw/blur
    - data/raw/clear
    outs:
    - data/proc/blur
    - data/proc/clear
  depth_gen:
    cmd: python ./utils/DepthMapGen.py
    deps:
    - data/proc/blur
    - data/proc/clear
    outs:
    - data/proc/depth
  split_and_rename_depth_files:
    cmd: python ./utils/SplitAndRenameDepthFiles.py
    deps:
    - data/proc/depth
    outs:
    - 'data/proc/depth_preview'