stages:
  proc_imgs:
    cmd: python ./utils/ImgProcess.py
    deps:
    - ./utils/ImgProcess.py
    - data/raw/blur
    - data/raw/clear
    outs:
    - data/proc/blur
    - data/proc/clear
  depth_gen:
    cmd: python ./utils/DepthMapGen.py
    deps:
    - data/proc/blur
    - data/proc/clear
    outs:
    - data/proc/depth