generator:
  in_channels: 4
  out_channels: 5
  additional_decode_layer: 0
  lambda_l1: 100
  lambda_vq: 1
  lambda_gan: 1
  lambda_commit: 0.25
  beta1: 0.5
  beta2: 0.999
  lr: 2e-4
  vqvae:
    additional_encode_layer: 2
    codebook_size: 1024
    codebook_len: 64
discriminator:
  input_nc: 7
  ndf: 64
  n_layers: 3
  lr: 2e-4
  beta1: 0.5
  beta2: 0.999
