data:
  data_dir: ${hydra:runtime.cwd}/data/report/
  batch_size: 8
  num_workers: 4
  img_size: 1024
  augment: True
  train_val_split: 0.8
  sync_transforms:
    rand_file_prob: 0.5
    rand_rotation_degree: 10
    colorJitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1