defaults:
  - data: default
  - model: default
  - train: default
  - utils: default

seed: 42
project_name: "dof_generation"
run_name: "${now:%Y-%m-%d_%H-%M-%S}"
checkpoint_dir: "checkpoints/"

data:
  data_dir: "data/"
  batch_size: 32
  num_workers: 4
  train_val_split: 0.8
  image_size: 256

model:
  lr: 0.0002
  lambda_l1: 100
  vae:
    input_dim: 4
    hidden_dim: 64
    latent_dim: 256
  generator:
    input_dim: 256
  discriminator:
    input_channels: 4 # RGB + Depth

train:
  monitor_metric: "total_g_loss"
  max_epochs: 100
  gpus: 1

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
