defaults:
  - data: default
  - model: default
  - train: default
  - utils: default

seed: 42
project_name: "dof_generation"
run_name: "${now:%Y-%m-%d_%H-%M-%S}"

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}